services: 
  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
